INSERT INTO UM_USER (UM_USER_NAME , UM_USER_PASSWORD , UM_SALT_VALUE , UM_CHANGED_TIME,UM_TENANT_ID) VALUES ('alice', 'JrWcajhOuVlbax1+pWAW+51izzscYrgb7zTf0RiDoaY=', '5YXbu7eY7hA1P6kTcRWOmw==', NOW(), -1234);

INSERT INTO UM_USER (UM_USER_NAME , UM_USER_PASSWORD , UM_SALT_VALUE , UM_CHANGED_TIME,UM_TENANT_ID) VALUES ('bob', 'GlA5IJ02bmIHz/WFVV/G200yBHn5o/wqzQgjqPdLKWs=', 'Z9SfI3wxmmWto2aYF1Vt4A==', NOW(), -1234);
